const ADD_POINT = 'ADD_POINT';
const RESET_POINTS = 'RESET_POINTS';
const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
const ADD_QUESTION = 'ADD_QUESTION';
const GET_RANDOM_QUESTION = 'GET_RANDOM_QUESTION'

export default {
ADD_POINT,
RESET_POINTS,
FETCH_QUESTIONS,
ADD_QUESTION,
GET_RANDOM_QUESTION
}