const HANDLE_ANSWER = 'HANDLE_ANSWER,'
const ADD_QUESTIONS = 'ADD_QUESTIONS';
const DRAW_QUESTION = 'DRAW_QUESTION';
const SET_CATEGORY = 'SET_CATEGORY';
const SET_MODE = 'SET_MODE';

export default {
HANDLE_ANSWER,
ADD_QUESTIONS,
DRAW_QUESTION,
SET_CATEGORY,
SET_MODE
}