const ADD_POINT = 'ADD_POINT';
const RESET_POINTS = 'RESET_POINTS';
const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
const ADD_QUESTIONS = 'ADD_QUESTIONS';
const DRAW_QUESTION = 'DRAW_QUESTION';
const GET_RANDOM_QUESTION = 'GET_RANDOM_QUESTION';
const ANSWER_QUESTION = 'ANSWER_QUESTION';

export default {
ADD_POINT,
RESET_POINTS,
FETCH_QUESTIONS,
ADD_QUESTIONS,
DRAW_QUESTION,
GET_RANDOM_QUESTION,
ANSWER_QUESTION
}