const HANDLE_ANSWER = 'HANDLE_ANSWER,'
const ADD_QUESTIONS = 'ADD_QUESTIONS';
const DRAW_QUESTION = 'DRAW_QUESTION';
const SET_GAME_DETAILS = 'SET_GAME_DETAILS';


export default {
HANDLE_ANSWER,
ADD_QUESTIONS,
DRAW_QUESTION,
SET_GAME_DETAILS
}