const ADMIN_LOGGEDIN = 'ADMIN_LOGGEDIN';
const ADMIN_LOGGEDOUT = 'ADMIN_LOGGEDOUT';
const USER_LOGGEDIN = 'USER_LOGGEDIN';
const USER_LOGGEDOUT = 'USER_LOGGEDOUT';

export default {
    ADMIN_LOGGEDIN,
    ADMIN_LOGGEDOUT,
    USER_LOGGEDIN,
    USER_LOGGEDOUT
}